language: node_js

node_js:
  - '10'

cache:
  yarn: true
  directories:
    - node_modules

install:
  - yarn

script:
  - commitlint-travis
  - yarn coveralls
  - git config --global user.name "${GH_NAME}"
  - git config --global user.email "${GH_EMAIL}"
  - echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc
  - cd docs && cd website && yarn install && GIT_USER="${GH_NAME}" yarn run publish-gh-pages

before_deploy:
  - yarn build
# NPM deploy
# deploy:
#   skip_cleanup: true
#   provider: npm
#   email: $EMAIL
#   api_key:
#     secure: $API_KEY
#   on:
#     tags: true
#     repo: Rocketseat/unform
